---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-grpc-clock-server
spec:
  selector:
    matchLabels:
     app: dummy-grpc-clock-server
  replicas: 1
  template:
    metadata:
      labels:
        app: dummy-grpc-clock-server
    spec:
      containers:
      - name: dummy-grpc-clock-server
        image: szaqal/dummy-grpc-clock-server:latest
        ports:
        - containerPort: 50051
---

apiVersion: v1
kind: Service
metadata:
  name: dummy-grpc-clock-server
spec:
  selector:
    app: dummy-grpc-clock-server
  type: NodePort
  ports:
  - port: 50051
    targetPort: 50051
    nodePort: 31051
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-grpc-clock-client
spec:
  selector:
    matchLabels:
     app: dummy-grpc-clock-client
  replicas: 1
  template:
    metadata:
      labels:
        app: dummy-grpc-clock-client
    spec:
      containers:
      - name: dummy-grpc-clock-client
        image: szaqal/dummy-grpc-clock-client:latest
        env:
        - name: SERVER_ADDRESS
          value: "dummy-grpc-clock-server.default.svc.cluster.local:50051"
