apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-http
spec:
  selector:
    matchLabels:
     app: dummy-http
  replicas: 2
  template:
    metadata:
      labels:
        app: dummy-http
    spec:
      containers:
      - name: dummy-http
        image: szaqal/dummy-http:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-http
spec:
  selector:
    app: dummy-http
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: dummy-http-gateway
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dummy-http
spec:
  hosts:
  - "*"
  gateways:
  - dummy-http-gateway
  http:
  - route:
    - destination:
        host: dummy-http.default.svc.cluster.local
