apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-http
spec:
  selector:
    matchLabels:
     app: dummy-http
  replicas: 1
  template:
    metadata:
      labels:
        app: dummy-http
    spec:
      containers:
      - name: dummy-http
        image: szaqal/dummy-http:latest
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: dummy-http
spec:
  selector:
    app: dummy-http
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31080
    protocol: TCP
