---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-grpc-clock-server
spec:
  selector:
    matchLabels:
     app: dummy-grpc-clock-server
  replicas: 1
  template:
    metadata:
      labels:
        app: dummy-grpc-clock-server
    spec:
      containers:
      - name: dummy-grpc-clock-server
        image: szaqal/dummy-grpc-clock-server:latest
        imagePullPolicy: Always
        env:
        - name: USE_TLS
          value: "false"
        ports:
        - containerPort: 50051

---
apiVersion: v1
kind: Service
metadata:
  name: dummy-grpc-clock-server
spec:
  selector:
    app: dummy-grpc-clock-server
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-grpc-clock-client
spec:
  selector:
    matchLabels:
     app: dummy-grpc-clock-client
  replicas: 1
  template:
    metadata:
      labels:
        app: dummy-grpc-clock-client
    spec:
      containers:
      - name: dummy-grpc-clock-client
        image: szaqal/dummy-grpc-clock-client:latest
        imagePullPolicy: Always
        env:
        - name: USE_TLS
          value: "false"
        - name: SERVER_ADDRESS
          value: "istio-ingressgateway.istio-system.svc.cluster.local:31399"

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: dummy-grpc-clock-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 31399
      name: grpc
      protocol: GRPC
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dummy-grpc-clock-server
spec:
  hosts:
  - "*"
  gateways:
  - dummy-grpc-clock-gateway
  http:
  - match:
    - port: 31399
    route:
    - destination:
        host: dummy-grpc-clock-server.default.svc.cluster.local
        port:
          number: 50051
          port: GRPC